name: "Checkout Demo"

on:
  workflow_dispatch:

jobs:
    demo_checkout:
        runs-on: "ubuntu-latest"
        steps:
            - name: "List Space"
              run: ls -la ${{ github.workspace }}

            - name: "Checkout Repository"
              uses: actions/checkout@v4

            - name: "List Space after Checkout"
              run: ls -la ${{ github.workspace }}
