name: "Conditional Steps"

on:
  workflow_dispatch:

jobs:
  conditional-step-job:
    runs-on: "ubuntu-latest"

    steps:
      - name: "This Step Will Always be Sucessfull"
        run: |
          echo "exit code 0"
          exit 0 # Sucessfull

      - name: "This Step Will Always Execute"
        if: ${{ success() }} # Implicit
        run: |
          echo "This will run because previous step exited with 0"

      - name: "This Step Will Always Fail"
        run: |
          echo "exit code 1"
          exit 1 # Failed

      - name: "This Step Will Never Execute"
        run: echo "This will never be echoed!"

      - name: "This Step Will Always be executed aswell"
        if: ${{ failure() }}
        run: echo "This Step Will execute because of the previous step failure"
