name: "Parallel Jobs"

on:
  workflow_dispatch:

jobs:
    linting:
        runs-on: "ubuntu-latest"
        steps:
            - name: "Linting"
              run: echo "Linting"

    unit_test:
        runs-on: "ubuntu-latest"
        steps:
            - name: "Unit Tests"
              run: echo "Performing Unit Tests"

    integration_tests:
        runs-on: "ubuntu-latest"
        steps:
            - name: "Set Environment"
              run : echo "Setting environment for Integration Tests"

            - name: "Execute Integration Tests"
              run: echo "Executing Integration Tests"