name: "Passing File"

on:
    workflow_dispatch:

jobs:
    upload-artifact-job:
        runs-on: "ubuntu-latest"
        steps:
            - name: "Checkout Source Code"
              uses: actions/checkout@v4

            - name: "Donwload Python"
              uses: actions/setup-python@v5
              with:
                python-version: "3.10"

            - name: "Install Tox"
              run: |
                pip install tox

            - name: "Run Unit Tests"
              run: |
                cd backend
                tox -e unit
                ls -la ${{github.workspace}}/backend

            - name: "Prepare File for Upload"
              run: |
                cd ${{github.workspace}}
                ls -la backend/.coverage
                head -n 5 backend/.coverage

                cp backend/.coverage backend/coverage.sqlite
                ls -la backend/coverage.sqlite

            - name: "Upload Artifact"
              uses: actions/upload-artifact@v4
              with:
                name: coverage
                path: ${{github.workspace}}/backend/coverage.sqlite

    download-artifact-job:
        runs-on: "ubuntu-latest"
        needs: ["upload-artifact-job"]
        steps:
            - name: "Download Artifact"
              uses: actions/download-artifact@v4
              with:
                name: coverage
                path: ${{github.workspace}}

            - name: "List Folder"
              run: |
                ls -la ${{github.workspace}}

